# Generated by Django 5.0.6 on 2024-06-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
