# Generated by Django 5.0.6 on 2024-06-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booked_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('beginner', 'Beginner Surfing'), ('intermediate', 'Intermediate Surfing'), ('advanced', 'Advanced Surfing'), ('mens', 'Men’s Surfing Classes'), ('womens', 'Women’s Surfing Classes'), ('kids', 'Kids Surfing Lessons'), ('junior', 'Junior Surfing Classes'), ('family', 'Family Surfing Classes'), ('senior', 'Senior Surfing Lessons'), ('couples', 'Couples Surfing Classes')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
    ]
